name: digantara
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  cool_stepper: ^1.2.1
  cupertino_icons: ^1.0.2
  dropdown_search: ^2.0.1
  flutter:
    sdk: flutter
  flutter_html: ^2.2.1
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.2+1
  font_awesome_flutter: ^9.2.0
  get: 4.6.1
  http: ^0.13.4
  image_picker: ^0.8.4+11
  shimmer: ^2.0.0
  timeago: ^3.2.2
  url_launcher: ^6.0.20
  webview_flutter: ^2.0.4

flutter_icons:
  image_path: "assets/images/brand.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#D02961"
  image: assets/images/brand.png
  android: true
  ios: true
  web: true

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
